### ISSUE TITLE
Switch to Limine

### ISSUE THREAD

**Issue by Andrej123456789** [wmthornton/YAFIX-x64-Main#2]
gnu-efi have problems on real hardaware

**Comment by wmthornton** [comment]
There is a method to "burn" the image to a USB stick and boot on an EFI machine without issues. However, if the processor is too new or there is over about 3gb of RAM the system will crash. These bugs are on the list to be addressed.

**Comment by Andrej123456789** [comment]
With Limine you can boot on machine over 3GB RAM

**Comment by wmthornton** [comment]
I'm not opposed to switching to Limine assuming the bootloader can be made to inter-operate with the DSYFX functions currently in place and be scaled with custom functions that further support DSYFX in future. That said, you're more than welcome to try to convert to Limine assuming the DSYFX inter-op isn't affected. I've created a "Limine-Bootloader" branch for you to test with and submit any PRs to - I just don't have the time at the moment to worry about switching bootloaders on top of the other kernel work being done.

**Comment by Andrej123456789** [comment]
I worked with Limine and I stuck with memory map and framebuffer info

**Comment by Andrej123456789** [comment]
https://github.com/wmthornton/YAFIX-x64-Main/pull/4

**Comment by Andrej123456789** [comment]
Here is my Limine Pull Request. I will close this issue
